language: node_js
node_js:
  - "10"

script:
  - npm install
  - npm run test

after_success:
  - npm install -g codeclimate-test-reporter
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
